# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Data.to.insights() 
tagline:             'Set of personal projects in Data Science and Machine Learning'
description:         
url:                 
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Marko Mitic
  url:               
  email:             miticm[at]gmail.com
  github:            mmitic
  linkedin:          dr-marko-mitic
# Custom vars
version:             1.0.0
