# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:                Data.to.discovery( ) 
tagline:             'Set of personal projects in Data Science and Machine Learning'
description:         
url:                 
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Marko Mitic
  url:               
  email:             miticm[at]gmail.com
  email_md5:         7085e66f82be0b794be80b4359df1ca6
  github:            mmitic
  linkedin:          dr-marko-mitic

# Custom vars
version:             1.0.0

github:
  repo:           https://github.com/mmitic
